version: '3.8'
services:
  react-refresher-service:
    build: .
    container_name: react-refresher-container
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true